"""
Exporting timetables to Excel and PDF.

There were no tests for exports before elective blocks, and adding the
per-student export meant refactoring the shared renderer - so the existing
whole-school export is covered here too, reading the generated files rather
than only their status codes. A test that checks for a 200 passes just as well
for a spreadsheet with the wrong lessons in it.

Student timetables: a student's timetable is the section's, filtered to the
common subjects plus only the option they chose from each block. No extra
solving - the section's timetable already holds every combination at once.
"""
import io
import itertools

import openpyxl
import pytest

from app.core.database import SessionLocal
from app.models.school import (
    ClassGroup, ElectiveBlock, ElectiveOption, Period, Subject, Teacher, Timetable,
    TimetableEntry,
)
from app.services.student_combinations import MAX_COMBINATIONS
from tests.conftest import create_school, signup


@pytest.fixture
def world(client):
    """11A over one day: two blocks and English, generated by hand so every
    cell is known.

      period 1: Block 1 - Physics (Rao) / Accounts (Khan)
      period 2: English (Verma)
      period 3: Block 2 - Chemistry (Das) / Economics (Nair) / Biology (Iyer)
    """
    _, headers = signup(client)
    school = create_school(client, headers)
    db = SessionLocal()
    try:
        sid = school["id"]
        periods = [Period(school_id=sid, day_of_week=0, order=o) for o in range(3)]
        subjects = {n: Subject(school_id=sid, name=n) for n in
                    ("Physics", "Accounts", "English", "Chemistry", "Economics", "Biology")}
        teachers = {n: Teacher(school_id=sid, name=n, qualified_subject_ids=[])
                    for n in ("Rao", "Khan", "Verma", "Das", "Nair", "Iyer")}
        a = ClassGroup(school_id=sid, grade="Grade 11", name="A")
        plain = ClassGroup(school_id=sid, grade="Grade 9", name="A")
        db.add_all([*periods, *subjects.values(), *teachers.values(), a, plain])
        db.commit()
        b1 = ElectiveBlock(school_id=sid, class_group_id=a.id, name="Block 1", periods_per_week=1,
                           options=[ElectiveOption(subject_id=subjects[n].id) for n in ("Physics", "Accounts")])
        b2 = ElectiveBlock(school_id=sid, class_group_id=a.id, name="Block 2", periods_per_week=1,
                           options=[ElectiveOption(subject_id=subjects[n].id)
                                    for n in ("Chemistry", "Economics", "Biology")])
        db.add_all([b1, b2])
        tt = Timetable(school_id=sid, status="draft", solver_status="optimal")
        db.add(tt)
        db.commit()
        rows = [
            ("Physics", "Rao", 0, b1), ("Accounts", "Khan", 0, b1),
            ("English", "Verma", 1, None),
            ("Chemistry", "Das", 2, b2), ("Economics", "Nair", 2, b2), ("Biology", "Iyer", 2, b2),
        ]
        for subject, teacher, period, block in rows:
            db.add(TimetableEntry(
                timetable_id=tt.id, class_group_id=a.id, subject_id=subjects[subject].id,
                teacher_id=teachers[teacher].id, period_id=periods[period].id,
                elective_block_id=block.id if block else None,
            ))
        db.commit()
        ids = {"tt": tt.id, "a": a.id, "plain": plain.id, "school": sid}
    finally:
        db.close()
    return ids, headers


def _export(client, w, headers, **params):
    query = "&".join(f"{k}={v}" for k, v in params.items())
    return client.get(f"/api/timetables/{w['tt']}/export?{query}", headers=headers)


def _sheets(content: bytes) -> dict[str, list[list]]:
    wb = openpyxl.load_workbook(io.BytesIO(content))
    return {ws.title: [[c.value for c in row] for row in ws.iter_rows()] for ws in wb.worksheets}


def _text(rows) -> str:
    return "\n".join(str(v) for row in rows for v in row if v)


# ---------------------------------------------------------------------------
# The whole-school export, which had no tests before
# ---------------------------------------------------------------------------


def test_the_school_export_has_a_sheet_per_section_and_per_teacher(client, world):
    w, h = world
    r = _export(client, w, h, format="xlsx")
    assert r.status_code == 200, r.text
    sheets = _sheets(r.content)
    assert "Grade 11 - A" in sheets
    assert {"Rao", "Khan", "Verma", "Das", "Nair", "Iyer"} <= set(sheets)


def test_a_section_with_nothing_scheduled_gets_no_sheet(client, world):
    w, h = world
    assert "Grade 9 - A" not in _sheets(_export(client, w, h, format="xlsx").content)


def test_the_section_sheet_shows_every_option_under_its_block_name(client, world):
    """One cell with three subjects in it needs to say why."""
    w, h = world
    sheet = _text(_sheets(_export(client, w, h, format="xlsx").content)["Grade 11 - A"])
    assert "Block 1" in sheet and "Block 2" in sheet
    for subject in ("Physics", "Accounts", "Chemistry", "Economics", "Biology", "English"):
        assert subject in sheet


def test_a_teacher_sheet_shows_only_their_own_lesson(client, world):
    w, h = world
    sheet = _text(_sheets(_export(client, w, h, format="xlsx").content)["Rao"])
    assert "Physics" in sheet
    assert "Accounts" not in sheet


def test_the_school_pdf_is_a_pdf(client, world):
    w, h = world
    r = _export(client, w, h, format="pdf")
    assert r.status_code == 200
    assert r.content.startswith(b"%PDF")


def test_an_unknown_format_is_refused(client, world):
    w, h = world
    assert _export(client, w, h, format="docx").status_code == 400


# ---------------------------------------------------------------------------
# Student timetables
# ---------------------------------------------------------------------------


def test_one_sheet_per_combination_of_choices(client, world):
    """Two options in Block 1 and three in Block 2 is six combinations."""
    w, h = world
    r = _export(client, w, h, format="xlsx", class_group_id=w["a"], student_combinations="true")
    assert r.status_code == 200, r.text
    sheets = _sheets(r.content)
    assert len(sheets) == 6
    expected = {f"{a} + {b}" for a, b in itertools.product(
        ("Physics", "Accounts"), ("Chemistry", "Economics", "Biology"))}
    labels = {name.split(". ", 1)[1] for name in sheets}
    assert labels == expected


def test_a_student_timetable_keeps_only_the_chosen_options(client, world):
    """The Physics + Biology student sits in Physics and Biology - not
    Accounts, not Chemistry or Economics - and still has English."""
    w, h = world
    sheets = _sheets(_export(client, w, h, format="xlsx", class_group_id=w["a"],
                             student_combinations="true").content)
    name = next(n for n in sheets if n.endswith("Physics + Biology"))
    sheet = _text(sheets[name])
    assert "Physics" in sheet and "Biology" in sheet and "English" in sheet
    for absent in ("Accounts", "Chemistry", "Economics"):
        assert absent not in sheet, absent


def test_a_student_timetable_is_not_labelled_as_a_block(client, world):
    """A student attends one subject in that period, so calling the cell
    "Block 1" would read as if they had a choice still to make."""
    w, h = world
    sheets = _sheets(_export(client, w, h, format="xlsx", class_group_id=w["a"],
                             student_combinations="true").content)
    name = next(n for n in sheets if n.endswith("Accounts + Economics"))
    assert "Block" not in _text(sheets[name][2:])  # past the title row


def test_every_combination_has_the_same_common_subjects(client, world):
    w, h = world
    sheets = _sheets(_export(client, w, h, format="xlsx", class_group_id=w["a"],
                             student_combinations="true").content)
    for name, rows in sheets.items():
        assert "English" in _text(rows), name


def test_the_title_names_the_section_and_the_combination(client, world):
    w, h = world
    sheets = _sheets(_export(client, w, h, format="xlsx", class_group_id=w["a"],
                             student_combinations="true").content)
    name = next(n for n in sheets if n.endswith("Physics + Chemistry"))
    assert sheets[name][0][0] == "Grade 11 - A — Physics + Chemistry"


def test_student_timetables_as_a_pdf(client, world):
    w, h = world
    r = _export(client, w, h, format="pdf", class_group_id=w["a"], student_combinations="true")
    assert r.status_code == 200
    assert r.content.startswith(b"%PDF")
    assert "student_timetables_Grade_11_A.pdf" in r.headers["content-disposition"]


def test_a_section_without_blocks_has_nothing_to_split(client, world):
    w, h = world
    r = _export(client, w, h, format="xlsx", class_group_id=w["plain"], student_combinations="true")
    assert r.status_code == 400
    assert "same for every student" in r.json()["detail"]


def test_student_timetables_need_a_section(client, world):
    w, h = world
    assert _export(client, w, h, format="xlsx", student_combinations="true").status_code == 400


def test_a_section_from_another_school_is_refused(client, world):
    w, h = world
    _, other = signup(client, email="other@else.com")
    other_school = create_school(client, other)
    foreign = client.post("/api/class-groups", json={"school_id": other_school["id"], "name": "Z"},
                          headers=other).json()["id"]
    r = _export(client, w, h, format="xlsx", class_group_id=foreign, student_combinations="true")
    assert r.status_code == 404


def test_an_absurd_number_of_combinations_is_refused_with_a_reason(client, world):
    """Past the cap the request is almost certainly a data-entry mistake, and
    producing it would look like the export had hung."""
    w, h = world
    db = SessionLocal()
    try:
        # Enough single-subject-pair blocks to exceed the cap: 2^10 = 1024.
        for i in range(10):
            a = Subject(school_id=w["school"], name=f"X{i}")
            b = Subject(school_id=w["school"], name=f"Y{i}")
            db.add_all([a, b])
            db.commit()
            db.add(ElectiveBlock(school_id=w["school"], class_group_id=w["a"], name=f"Extra {i}",
                                 periods_per_week=1,
                                 options=[ElectiveOption(subject_id=a.id), ElectiveOption(subject_id=b.id)]))
        db.commit()
    finally:
        db.close()
    assert 6 * 2 ** 10 > MAX_COMBINATIONS
    r = _export(client, w, h, format="xlsx", class_group_id=w["a"], student_combinations="true")
    assert r.status_code == 400
    assert "combinations" in r.json()["detail"]
