"""add timetables.error_explanation

Revision ID: 7c8ff2e54a7d
Revises: 3bae44889dc8
Create Date: 2026-09-16 02:02:46.584796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8ff2e54a7d'
down_revision: Union[str, None] = '3bae44889dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('error_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetables', 'error_explanation')
    # ### end Alembic commands ###
