"""add periods.is_break

Revision ID: 918de61b7eb0
Revises: 7c8ff2e54a7d
Create Date: 2026-09-24 01:32:01.277790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918de61b7eb0'
down_revision: Union[str, None] = '7c8ff2e54a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('is_break', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periods', 'is_break')
    # ### end Alembic commands ###
