"""track constraint source text and parser

Revision ID: f0d72579b20b
Revises: 918de61b7eb0
Create Date: 2026-09-24 01:54:57.068488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d72579b20b'
down_revision: Union[str, None] = '918de61b7eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constraints', sa.Column('source_text', sa.Text(), nullable=True))
    op.add_column('constraints', sa.Column('parsed_by', sa.String(), nullable=True))
    op.add_column('constraints', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constraints', 'created_at')
    op.drop_column('constraints', 'parsed_by')
    op.drop_column('constraints', 'source_text')
    # ### end Alembic commands ###
