"""
FastAPI application entrypoint.

Run locally with:
    uvicorn app.main:app --reload

Interactive API docs are then available at http://localhost:8000/docs
(auto-generated by FastAPI from the route/schema definitions below).
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config import settings
from app.core.database import Base, engine
from app.models import school, user  # noqa: F401 - imported so tables register on Base
from app.routers import (
    auth,
    class_groups,
    constraints,
    invites,
    periods,
    rooms,
    schools,
    setup_extraction,
    solver,
    subjects,
    substitutions,
    teachers,
    timetables,
)

# Creates tables if they don't exist yet. Fine for local dev; production
# should use Alembic migrations instead (see docs/GETTING_STARTED.md).
Base.metadata.create_all(bind=engine)

app = FastAPI(title=settings.app_name, debug=settings.debug)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins.split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(schools.router)
app.include_router(invites.router)
app.include_router(subjects.router)
app.include_router(rooms.router)
app.include_router(periods.router)
app.include_router(teachers.router)
app.include_router(class_groups.router)
app.include_router(constraints.router)
app.include_router(timetables.router)
app.include_router(solver.router)
app.include_router(substitutions.router)
app.include_router(setup_extraction.router)


@app.get("/health")
def health_check():
    """Basic liveness check used by hosting platforms (Railway/Render)."""
    return {"status": "ok"}
