"""
FastAPI application entrypoint.

Run locally with:
    alembic upgrade head          # create/update the schema first
    uvicorn app.main:app --reload

Interactive API docs are then available at http://localhost:8000/docs
(auto-generated by FastAPI from the route/schema definitions below).
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware

from app.core.config import settings
from app.core.observability import init_sentry, log_llm_availability
from app.core.rate_limit import limiter, rate_limit_exceeded_handler
from app.models import school, user  # noqa: F401 - registers mappers before first request
from app.routers import (
    auth,
    class_groups,
    constraints,
    invites,
    periods,
    rooms,
    schools,
    setup_extraction,
    solver,
    subjects,
    substitutions,
    teachers,
    timetables,
)

# No Base.metadata.create_all() here on purpose. The schema is owned by the
# Alembic migrations in alembic/versions/ and applied with
# `alembic upgrade head` - locally by hand, in production by Railway's
# pre-deploy command (see docs/DEPLOYMENT.md).
#
# Leaving create_all() in alongside migrations is actively harmful: it only
# ever creates *missing tables*, so against a database that migrations
# haven't touched it would silently reconstruct a schema with no
# alembic_version row - putting the database back outside Alembic's
# control, and making the next `upgrade head` fail against tables that
# already exist.

# Before the app is constructed, so anything that fails during startup is
# still reported. No-op unless SENTRY_DSN is set.
init_sentry()
log_llm_availability()

app = FastAPI(title=settings.app_name, debug=settings.debug)

# slowapi reads the limiter off app.state; the middleware is what makes the
# @limiter.limit decorators in the routers take effect.
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, rate_limit_exceeded_handler)
app.add_middleware(SlowAPIMiddleware)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins.split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(schools.router)
app.include_router(invites.router)
app.include_router(subjects.router)
app.include_router(rooms.router)
app.include_router(periods.router)
app.include_router(teachers.router)
app.include_router(class_groups.router)
app.include_router(constraints.router)
app.include_router(timetables.router)
app.include_router(solver.router)
app.include_router(substitutions.router)
app.include_router(setup_extraction.router)


@app.get("/health")
def health_check():
    """Basic liveness check used by hosting platforms (Railway/Render)."""
    return {"status": "ok"}
